project:
  type: website
  output-dir: docs

website:
  title: "Final Project"
  navbar:
    left:
      - href: about.qmd
        text: Project
format:
  html:
    theme: flatly
    css: styles.css
    toc: true



