project:
  type: website
  output-dir: docs

website:
  title: "Building Edtech for Mental Wellbeing"
  navbar:
    left:
      - href: index.qmd
        text: Abstract
      - href: about.qmd
        text: Findings
      - href: conclusions.qmd
        text: Future Directions and Limitations
      - href: sources.qmd
        text: Data Sources
        
    right:
      - icon: github
        href: https://github.com/AviannaBui/website_project_212
        
format:
  html:
    theme: flatly
    css: styles.css
    toc: true



