---
title: "Future Directions and Limitations"
---

## Suggestions for Future Digital Learning Platform Design

### Learning time

- Easy navigation and tech support to cut down unnecessary screen time
- Projects and assignments should be multimodal (not all digital products)
- Materials and participation should always be available at student’s expense 

### Social connection
- Create teamwork opportunities and unmonitored spaces for students to converse and exchange.
- Zoom, breakout rooms with not too few students.


###  Online class comfortability
- Needs more investigation due to highly-interpretative essence of “comfortability”

## Limitations & Ethical Considerations

All datasets utilize a survey format, which is highly subjective and might lead to unreliable results. In addition, due to the cross-sectional design, we are unable to infer the causal impact and changes over time when it comes to the relationship between edtech and mental well-being. 

More importantly, the students participating in these surveys are not representative of the wider student populations in these three countries. First, some survey questions ignore the experiences of students from marginalized communities e.g. the Jordanian and Colombian datasets only recorded binary gender in their questionnaire, effectively excluding those identifying as non-binary or just not subscribing to a binary gender framework. Second, since the surveys are collected online, students from disadvantaged socioeconomic backgrounds with no or unreliable access to Internet or online learning tools are either excluded or not well-represented in these results. However, it is these individuals that are more susceptible to both physical and mental health risks during the COVID-19 pandemic and are more likely to struggle with the transition to online learning. For that reason, we need to be mindful and inclusive of the perspectives of students without access to a platform to share their experiences when advocating for their educational needs and designing a more accessible and considerate online learning tools and environment. 